<?php

if (isset($_POST['pdfExport-submit'])) {
    require('database.php');
    require('statisticsPHP.php');

    //Libraria pentru a genera PDF
    require('fpdf17/fpdf.php');

    //A4 width : 219mm
    //default margin : 10mm each side
    //writable horizontal : 219-(10*2)=189mm

    //create pdf object
    $pdf = new FPDF('P', 'mm', 'A4');
    //adaug o noua pagina
    $pdf->AddPage();

    //set font to arial, bold, 14pt
    $pdf->SetFont('Arial', 'B', 14);

    //Cell(width , height , text , border , end line , [align] )

    $pdf->Cell(130, 5, 'GaMa STATISTICS', 0, 0); //Iasi, Str. Aioanesei Adrian, Nr. 69
    $pdf->Cell(59, 5, '', 0, 1); //end of line

    //set font to arial, regular, 12pt
    $pdf->SetFont('Arial', '', 12);

    $pdf->Cell(130, 5, '[Str. Ioanesei Adrian]', 0, 0);
    $pdf->Cell(59, 5, '', 0, 1); //end of line

    $pdf->Cell(130, 5, '[Iasi, Romania]', 0, 0);
    $pdf->Cell(25, 5, 'Date', 0, 0);

    $sqlGetDate="SELECT NOW() as date";
    $result = mysqli_query($conn, $sqlGetDate);
    $row = $result->fetch_assoc();
    $date = $row['date'];

    $pdf->Cell(10, 5, $date, 0, 1); //end of line

    $pdf->Cell(130, 5, 'Generated by', 0, 1);
    $pdf->Cell(25, 5, 'ADMIN', 0, 1);

    //dummy empty cells
    $pdf->Cell(189, 10, '', 0, 1); //end of line
    $pdf->Cell(189, 10, '', 0, 1); //end of line

    //invoice contents
    $pdf->SetFont('Arial', 'B', 12);

    $pdf->Cell(130, 5, 'Description', 1, 0);
    //$pdf->Cell(25, 5, 'Taxable', 1, 0);
    $pdf->Cell(34, 5, 'STATISTICS', 1, 1); //end of line

    $pdf->SetFont('Arial', '', 12);

    //Numbers are right-aligned so we give 'R' after new line parameter

    $pdf->Cell(130, 5, 'Number of users', 1, 0);
    $pdf->Cell(34, 5, $numberOfTotalUsers, 1, 1, 'R');

    $pdf->Cell(130, 5, '% of users that are male', 1, 0);
    $pdf->Cell(34, 5, round($percentOfMales, 2), 1, 1, 'R');

    $pdf->Cell(130, 5, '% of users that are female', 1, 0);
    $pdf->Cell(34, 5, round($percentOfFemales, 2), 1, 1, 'R');

    $pdf->Cell(130, 5, '% of users that have 1-13 years', 1, 0);
    $pdf->Cell(34, 5, round($percentOf1_13, 2), 1, 1, 'R');

    $pdf->Cell(130, 5, '% of users that have 14-70 years', 1, 0);
    $pdf->Cell(34, 5, round($percentOf14_70, 2), 1, 1, 'R');

    $pdf->Cell(130, 5, '% of users that have 71-99 years', 1, 0);
    $pdf->Cell(34, 5, round($percentOf71_99, 2), 1, 1, 'R');

    $pdf->Cell(130, 5, 'Number of games', 1, 0);
    $pdf->Cell(34, 5, $numberTotalGames, 1, 1, 'R');

    $pdf->Cell(130, 5, '% of digital games', 1, 0);
    $pdf->Cell(34, 5, round($precentOfDigitalGames, 2), 1, 1, 'R');

    $pdf->Cell(130, 5, '% of board games', 1, 0);
    $pdf->Cell(34, 5, round($percentOfBoardGames, 2), 1, 1, 'R');

    //output the result
    $pdf->Output();
}
